Repository uabrc/uabrc.github.io, pull requests merged in 2024-11, with the labels that each got.

#850 Added "eligible" to scratch policy
  docs/data_management/storage.md
Labels: pr: merge

#852 Markdown formatting in csv table
  docs/contributing/contributor_guide.md
Labels: pr: merge

#857 Update the MATLAB OOD form screenshot
  docs/cheaha/open_ondemand/images/ood_matlab_form.png
  docs/cheaha/open_ondemand/ood_matlab.md
Labels: pr: merge

#851 Information for users to access submitted ServiceNow tickets
  docs/images/servicenow_landing_page.png
  docs/images/servicenow_landing_page_tickets.png
  docs/index.md
Labels: pr: needs changes

#841 Fix missing urls and update checker
  .linkcheckerrc
  docs/cheaha/open_ondemand/hpc_desktop.md
  docs/workflow_solutions/git_collaboration.md
  docs/workflow_solutions/using_anaconda.md
  scripts/linkchecker.py
Labels: pr: review
